version: 2

registries:
  github-pagopa:
    type: maven-repository
    url: https://maven.pkg.github.com/pagopa
    username: "mil-github-bot"
    password: "${{ secrets.MIL_BOT_TOKEN }}"

updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - github-pagopa
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      non-major-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"