name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
  workflow_dispatch:

jobs:

  checkout:
    name: 🔖 Checkout Repository
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          ref: ${{ github.ref_name }}

  payments-flow-release:
    name: 🚀 Release
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - name: 🚀 release + docker
        # https://github.com/pagopa/github-actions-template/releases/tag/v2.0.0
        uses: pagopa/github-actions-template/payments-flow-release@b825ee193430395706a4a7e580b8435bdded0227
        with:
          current_branch: ${{ github.ref_name }}
